#!/usr/bin/python
from subprocess import Popen
import sys
import os

filename = sys.argv[1]
while True:
    print("\nStarting " + filename)
    p = Popen("python " + filename, shell=True)
    p.wait()
    #os.system('taskkill.exe /im chromedriver.exe /f')